#!/bin/sh

set -e

remote_host=$1

if [ x"$remote_host" = x ] ; then
    echo 'Usage: deploy <host to deploy to>'
fi

echo Deploying to $remote_host

# On BSDish systems this will create a file with literal Xs in its name
# followed by random letters, but I can live with that.
tmp_dir=$(mktemp -t tmp.XXXXXXXX)

ssh $remote_host mkdir $tmp_dir
scp -r -q code conf feeds site $remote_host:$tmp_dir
ssh -t $remote_host sudo $tmp_dir/code/deploy-remote
ssh $remote_host rm -rf $tmp_dir
