#!/bin/sh

# When testing, sometimes it's nice to have man pages available when
# running in driver mode. This does that, assuming you have a
# public-umbrella as a peer of rabbitmq-website.

SERVER=../rabbitmq-public-umbrella/rabbitmq-server

if [ ! -d ${SERVER} ] ; then
    echo ${SERVER} not found
    exit 1
fi

mkdir -p site/man
make -C ${SERVER} docs_all

for f in ${SERVER}/docs/*.man.xml ; do
    ln -s ../../$f site/man
done
