/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docsSidebar: [
    {
      type: 'link',
      label: 'Welcome to Open Source RabbitMQ Documentation',
      href: 'https://www.rabbitmq.com/documentation.html',
    },
    {
      type: 'link',
      label: 'How Can I Get RabbitMQ',
      href: 'https://www.rabbitmq.com/documentation.html',
    },
    {
      type: 'link',
      label: 'Support Available for RabbitMQ',
      href: 'https://www.rabbitmq.com/documentation.html',
    },
    {
      type: 'category',
      label: 'What is New in RabbitMQ Releases',
      items: [
        'whats-new',
        {
          type: 'link',
          label: 'New in 4.0',
          href: 'https://www.rabbitmq.com/documentation.html',
        },
        {
          type: 'link',
          label: 'New in 3.13',
          href: 'https://www.rabbitmq.com/documentation.html',
        },        
        ],
    },
        {
          type: 'link',
          label: 'Deprecated and Removed Features and Functions',
          href: 'https://www.rabbitmq.com/documentation.html',
        },
        {
          type: 'link',
          label: 'Getting Started Tutorials',
          href: 'https://www.rabbitmq.com/documentation.html',
        }, 
        {
          type: 'link',
          label: 'How to Install RabbitMQ',
          href: 'https://www.rabbitmq.com/documentation.html',
        }  
    {
      type: 'category',
      label: 'Server Documentation',
      items: [
        'admin-guide',
        {
          type: 'category',
          label: 'Configuration',
          items: [
            'configure',
            {
              type: 'doc',
              id: 'relocate',
              label: 'File Locations',
            },
            'logging',
            {
              type: 'doc',
              id: 'persistence-conf',
              label: 'Persistence',
            },
            {
              type: 'doc',
              id: 'networking',
              label: 'Networking',
            },
            {
              type: 'doc',
              id: 'parameters',
              label: 'Parameters and Policies',
            },
          ],
        },
        {
          type: 'doc',
          id: 'management',
          label: 'Management UI',
        },
        'monitoring',
        'production-checklist',
        {
          type: 'category',
          label: 'TLS Support',
          items: [
            'ssl',
            {
              type: 'doc',
              id: 'troubleshooting-ssl',
              label: 'Troubleshooting TLS',
            },
            {
              type: 'doc',
              id: 'clustering-ssl',
              label: 'TLS for Inter-node (Clustering) Traffic',
            },
          ],
        },
        'streams',
        'feature-flags',
        'distributed',
        {
          type: 'category',
          label: 'Clustering',
          items: [
            'clustering',
            {
              type: 'doc',
              id: 'cluster-formation',
              label: 'Cluster Formation',
            },
            {
              type: 'doc',
              id: 'ha',
              label: 'Classic Queue Mirroring',
            },
            {
              type: 'doc',
              id: 'partitions',
              label: 'Clustering and Network Partitions',
            },
            {
              type: 'doc',
              id: 'nettick',
              label: 'Net Tick Time',
            },
            {
              type: 'doc',
              id: 'clustering-ssl',
              label: 'TLS for Inter-node (Clustering) Traffic',
            },
            {
              type: 'link',
              label: 'Inter-node Traffic Compression',
              href: 'https://www.rabbitmq.com/clustering-compression.html',
            },
          ],
        },
        {
          type: 'doc',
          id: 'reliability',
          label: 'Reliable Delivery',
        },
        {
          type: 'category',
          label: 'Schema Definition Export and Import',
          items: [
            'definitions',
            {
              type: 'link',
              label: 'Warm standby Using Definition Replication',
              href: 'https://www.rabbitmq.com/definitions-standby.html',
            },
          ],
        },
        'backup',
        {
          type: 'category',
          label: 'Alarms',
          items: [
            {
              type: 'doc',
              id: 'alarms',
              label: 'Alarms',
            },
            'memory',
            {
              type: 'doc',
              id: 'disk-alarms',
              label: 'Disk Alarms',
            },
            {
              type: 'doc',
              id: 'memory-use',
              label: 'Memory Use',
            },
            'flow-control',
          ],
        },
        {
          type: 'doc',
          id: 'memory-use',
          label: 'Memory Use',
        },
        {
          type: 'category',
          label: 'Alarms',
          items: [
            {
              type: 'doc',
              id: 'networking',
              label: 'Networking',
            },
            {
              type: 'doc',
              id: 'troubleshooting-networking',
              label: 'Troubleshooting Networking',
            },
          ]
        },
        'vhosts',
        {
          type: 'doc',
          id: 'access-control',
          label: 'Access Control (Authorisation)',
        },
        'authentication',
        {
          type: 'doc',
          id: 'ldap',
          label: 'LDAP',
        },
        {
          type: 'doc',
          id: 'lazy-queues',
          label: 'Lazy Queues',
        },
        {
          type: 'doc',
          id: 'event-exchange',
          label: 'Internal Event Exchange',
        },
        {
          type: 'doc',
          id: 'firehose',
          label: 'Firehose (Message Tracing)',
        },
        {
          type: 'category',
          label: 'Manual Pages',
          items: [
            'manpages',
            {
              type: 'doc',
              id: 'man/rabbitmqctl.8',
              label: 'rabbitmqctl',
            },
            {
              type: 'doc',
              id: 'man/rabbitmq-diagnostics.8',
              label: 'rabbitmq-diagnostics',
            },
            {
              type: 'doc',
              id: 'man/rabbitmq-plugins.8',
              label: 'rabbitmq-plugins',
            },
            {
              type: 'doc',
              id: 'man/rabbitmq-upgrade.8',
              label: 'rabbitmq-upgrade',
            },
            {
              type: 'doc',
              id: 'man/rabbitmq-queues.8',
              label: 'rabbitmq-queues',
            },
            {
              type: 'doc',
              id: 'man/rabbitmq-streams.8',
              label: 'rabbitmq-streams',
            },
            {
              type: 'doc',
              id: 'man/rabbitmq-server.8',
              label: 'rabbitmq-server',
            },
            {
              type: 'doc',
              id: 'man/rabbitmq-service.8',
              label: 'rabbitmq-service',
            },
            {
              type: 'doc',
              id: 'man/rabbitmq-echopid.8',
              label: 'rabbitmq-echopid',
            },
            {
              type: 'doc',
              id: 'man/rabbitmq-env.conf.5',
              label: 'rabbitmq-env.conf',
            },
          ],
        },
        {
          type: 'doc',
          id: 'windows-quirks',
          label: 'Windows Quirks',
        },
      ],
    },
    {
      type: 'category',
      label: 'Client Documentation',
      items: [
        'clients',
        {
          type: 'category',
          label: 'Java Client Guide',
          items: [
            {
              type: 'doc',
              id: 'api-guide',
              label: 'Java Client Guide',
            },
            {
              type: 'doc',
              id: 'java-tools',
              label: 'Java Client Tools',
            },
          ],
        },
        {
          type: 'category',
          label: 'JMS Client',
          items: [
            {
              type: 'doc',
              id: 'jms-client',
              label: 'JMS Client',
            },
            {
              type: 'link',
              label: 'JMS Client Spec Compliance',
              href: 'https://github.com/rabbitmq/rabbitmq-jms-client/blob/main/jms-client-compliance.md',
            },
          ],
        },
        {
          type: 'doc',
          id: 'dotnet-api-guide',
          label: '.NET Client Guide',
        },
        {
          type: 'doc',
          id: 'erlang-client-user-guide',
          label: 'Erlang Client Guide',
        },
        {
          type: 'doc',
          id: 'heartbeats',
          label: 'Heartbeats',
        },
        {
          type: 'doc',
          id: 'amqp-0-9-1-reference',
          label: 'AMQP 0-9-1 Reference',
        },
        {
          type: 'doc',
          id: 'uri-spec',
          label: 'AMQP 0-9-1 URI Spec',
        },
      ]
    },
  ],
};

export default sidebars;
