// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  kubernetesSidebar: [
    {
      type: 'category',
      label: 'Kubernetes Operator',
      link: {type: 'doc', id: 'operator/operator-overview'},
      items: [
        {
          type: 'doc',
          id: 'operator/quickstart-operator',
          label: 'Quickstart',
        },
        {
          type: 'doc',
          id: 'operator/install-operator',
          label: 'Install Operator',
        },
        {
          type: 'doc',
          id: 'operator/configure-operator-defaults',
          label: 'Configure defaults',
        },
        {
          type: 'doc',
          id: 'operator/kubectl-plugin',
          label: 'kubectl Plugin',
        },
        {
          type: 'doc',
          id: 'operator/using-operator/index',
          label: 'Using Operator',
        },
        {
          type: 'doc',
          id: 'operator/operator-monitoring',
          label: 'Monitoring',
        },
        {
          type: 'doc',
          id: 'operator/troubleshooting-operator',
          label: 'Troubleshooting',
        },
        {
          type: 'doc',
          id: 'operator/upgrade-operator',
          label: 'Upgrade Operator',
        },
      ],
    },
    {
      type: 'category',
      label: 'Kubernetes Topology Operator',
      items: [
        {
          type: 'doc',
          id: 'operator/install-topology-operator',
          label: 'Install Topology Operator',
        },
        {
          type: 'doc',
          id: 'operator/using-topology-operator',
          label: 'Using Topology Operator',
        },
        {
          type: 'doc',
          id: 'operator/tls-topology-operator',
          label: 'TLS Support',
        },
        {
          type: 'doc',
          id: 'operator/troubleshooting-topology-operator',
          label: 'Troubleshooting',
        },
      ],
    },
  ],
};

export default sidebars;
