#!/bin/sh

set -e
cd `dirname $0`

rm -f /etc/cron.d/mirror-rabbit-feeds
a2dissite www.rabbitmq.com
/etc/init.d/apache2 restart
rm /etc/apache2/sites-available/www.rabbitmq.com
rm -rf /srv/www.rabbitmq.com
