#!/usr/bin/env python3
# coding=utf-8

import render
import sys
import os
import os.path
import shutil
import posixpath


def usage():
    print("Usage: compile <in-dir> <out-dir> <mode> <version> [<file>]")
    exit(1)


def main():
    if len(sys.argv) < 4:
        usage()
    in_dir = sys.argv[1]
    render.SITE_DIR = in_dir
    out_dir = sys.argv[2]
    site_mode = sys.argv[3]
    if site_mode == 'previous':
        version = sys.argv[4]
        rest = sys.argv[5:]
    else:
        version = None
        rest = sys.argv[4:]
    if len(rest) == 1:
        f = rest[0]
        handle_file(in_dir, f, os.path.join(out_dir, f), site_mode, version)
    elif len(rest) == 0:
        for in_path, dirs, files in os.walk(in_dir):
            path = relpath(in_path, in_dir)
            out_path = os.path.join(out_dir, path)
            if not os.path.exists(out_path):
                os.makedirs(out_path)
                for f in files:
                    handle_file(in_dir,
                                os.path.normpath(os.path.join(path, f)),
                                os.path.join(out_path, f),
                                site_mode, version)
    else:
        usage()
    print("")


def handle_file(in_dir, in_f, out_f, site_mode, version):
    ext = os.path.splitext(in_f)[1].lower()
    if (ext == '.xml' and not blacklist(in_f)) or ext == '.md':
        render_file(in_f, out_f, site_mode, version)
    elif ext == '.xsl' or ext.endswith('~'):
        pass
    else:
        shutil.copyfile(os.path.join(in_dir, in_f), out_f)
        sys.stdout.write(".")


def blacklist(f):
    return f.startswith('resources/specs/')


def render_file(in_f, out_f, site_mode, version):
    try:
        rendered = render.render_page('/' + html_ext(in_f), site_mode, version).encode('utf-8')
    except Exception as e:
        print("\n\nException rendering {0}".format(in_f))
        raise e
    with open(html_ext(out_f), 'wb') as f:
        f.write(rendered)
    sys.stdout.write("#")


def html_ext(f):
    return os.path.splitext(f)[0] + '.html'


# This was necessary in the Python 2.x days and taken from
# http://www.saltycrane.com/blog/2010/03/ospathrelpath-source-code-python-25/

def relpath(path, start):
    """Return a relative version of a path"""
    if not path:
        raise ValueError("no path specified")
    start_list = posixpath.abspath(start).split(posixpath.sep)
    path_list = posixpath.abspath(path).split(posixpath.sep)
    # Work out how much of the filepath is shared by start and path.
    i = len(posixpath.commonprefix([start_list, path_list]))
    rel_list = [posixpath.pardir] * (len(start_list)-i) + path_list[i:]
    if not rel_list:
        return posixpath.curdir
    return posixpath.join(*rel_list)


if __name__ == "__main__":
    main()
