#!/bin/bash

set -e
cd `dirname $0`
cd ..

mode_version=$1
mode=${mode_version%%_*}
if [[ "$mode_version" == *_* ]] ; then
    version=${mode_version#*_}
else
    version=""
fi
version_path=${version}/
site=${mode}.rabbitmq.com
site_dir=/srv/${site}

if [ $mode = www ] ; then
    releases_dir=/home/rabbitmq/extras/releases/

    # Which user to mirror feeds as?  Default to the rabbitmq user, who by
    # convention owns the release deliverables dir.
    mirror_user=rabbitmq
    if ! id -u "$mirror_user" >/dev/null 2>&1 ; then
    # Otherwise, try the user running sudo deploy
        mirror_user="$SUDO_USER"
        if ! id -u "$mirror_user" >/dev/null 2>&1 ; then
            echo "Not sure which user to mirror feeds as" 1>&2
            exit 1
        fi
    fi

    echo "Feeds will be mirrored by the user $mirror_user" 1>&2

    # Find the corresponding group
    mirror_group=$(id -ng $mirror_user)

    xsltproc --novalid site/feed-atom.xsl site/news.xml > site/news.atom
elif [ $mode = previous ] ; then
    releases_dir=/home/rabbitmq/extras/releases/
else
    releases_dir=/home/rabbitmq/extras/nightlies/
fi

rm -rf $site_dir/site-src $site_dir/code
if [ $mode = previous ] ; then
    rm -rf $site_dir/site/youngest
    rm -rf $site_dir/site/${version_path}
else
    rm -rf $site_dir/site
fi

mkdir -p $site_dir $site_dir/feeds
chown -R $mirror_user.$mirror_group $site_dir/feeds
cp -r code $site_dir
cp -r site $site_dir/site-src

# TODO that "current" link is not created for nightlies
if [ $mode = www ] ; then
    if [ -d ${releases_dir}/rabbitmq-server/current/ ]; then
        cp -r ${releases_dir}/rabbitmq-server/current/man $site_dir/site-src/man
    fi
elif [ $mode = previous ] ; then
    version_pattern=${version/_/\.}
    version_pattern=${version_pattern%_*}*
    youngest_match=$(ls -d1v ${releases_dir}/rabbitmq-server/$version_pattern | tail -n 1)
    if [ -d $youngest_match ]; then
        cp -r $youngest_match/man $site_dir/site-src/man
    fi
fi

./code/compile $site_dir/site-src $site_dir/site/$version $mode_version

csplit -s -f part $site_dir/site/${version_path}templates/index.html /header-footer-horizon/
mv part00 $site_dir/site/${version_path}templates/index-header.html
tail -n +2 part01 > $site_dir/site/${version_path}templates/index-footer.html
rm $site_dir/site/${version_path}templates/index.html part*

if [ $mode = previous ] ; then
    youngest_dir=$(ls -d1v $site_dir/site/v* | tail -n 1)
    ln -sf $site_dir/site/$(basename ${youngest_dir}) $site_dir/site/youngest
fi

chown $mirror_user:$mirror_group $site_dir/site/index.html

if [ $mode = www ] ; then
    if [ -d /usr/share/wordpress/wp-content/themes/rabbitmq ]; then
        rm -rf /usr/share/wordpress/wp-content/themes/rabbitmq
        cp -r wordpress-theme /usr/share/wordpress/wp-content/themes/rabbitmq
    fi
fi

cp conf/robots.txt-$mode $site_dir/site/robots.txt

if [ -d /etc/apache2/sites-available/ ]; then
    cp conf/${site}* /etc/apache2/sites-available/
    a2ensite ${site}
    /etc/init.d/apache2 reload
fi

if [ $mode = www ] ; then
    if [ ! -e /etc/apache2/sites-enabled/www.rabbitmq.com-ssl ]; then
        echo "*** Note site www.rabbitmq.com-ssl is not enabled. Please enable manually if necessary. ***"
    fi

    sed "s|@USER@|$mirror_user|" <conf/mirror-rabbit-feeds.cron >/etc/cron.d/mirror-rabbit-feeds
fi
