#!/bin/bash

set -e
cd `dirname $0`
cd ..

mode=$1
version=$2
site=${mode}.rabbitmq.com
site_dir=/srv/${site}

if [ $mode = www ] ; then
    community_plugins_dir=/home/rabbitmq/extras/community-plugins/
    releases_dir=/home/rabbitmq/extras/releases/

    # Which user to mirror feeds as?  Default to the rabbitmq user, who by
    # convention owns the release deliverables dir.
    mirror_user=rabbitmq
    if ! id -u "$mirror_user" >/dev/null 2>&1 ; then
    # Otherwise, try the user running sudo deploy
        mirror_user="$SUDO_USER"
        if ! id -u "$mirror_user" >/dev/null 2>&1 ; then
            echo "Not sure which user to mirror feeds as" 1>&2
            exit 1
        fi
    fi

    echo "Feeds will be mirrored by the user $mirror_user" 1>&2

    # Find the corresponding group
    mirror_group=$(id -ng $mirror_user)

    xsltproc --novalid site/feed-atom.xsl site/news.xml > site/news.atom

    mkdir -p ${community_plugins_dir}
    ./code/find-community-plugins ${community_plugins_dir} site
elif [ $mode = previous ] ; then
    releases_dir=/home/rabbitmq/extras/releases/
else
    releases_dir=/home/rabbitmq/extras/nightlies/
fi

old_dir=`mktemp -d`
build_dir=`mktemp -d`

rm -rf $site_dir/site-src $site_dir/code ${build_dir}

mkdir -p $site_dir $site_dir/feeds
chown -R $mirror_user.$mirror_group $site_dir/feeds
cp -r code $site_dir
cp -r site $site_dir/site-src

# TODO that "current" link is not created for nightlies
if [ $mode = www ] ; then
    true
elif [ $mode = previous ] ; then
    version_pattern=${version/_/\.}
    version_pattern=${version_pattern%_*}
    version_pattern=${version_pattern//./\\.}\\.[0-9]
    youngest_match=$(find ${releases_dir}/rabbitmq-server -maxdepth 1 -type d -name "$version_pattern" | sort -V | tail -n 1)
    if [ x$youngest_match = x ] ; then
        echo "*** Note manpages not found. Please copy manually if necessary. ***"
    else
        cp -r $youngest_match/man $site_dir/site-src/man
    fi
fi

./code/compile $site_dir/site-src ${build_dir} $mode $version

csplit -s -f part ${build_dir}/templates/index.html /header-footer-horizon/
mv part00 ${build_dir}/templates/index-header.html
tail -n +2 part01 > ${build_dir}/templates/index-footer.html
rm ${build_dir}/templates/index.html part*

if [ $mode = www ] ; then
    chown $mirror_user:$mirror_group ${build_dir}/index.html
    if [ -d /usr/share/wordpress/wp-content/themes/rabbitmq ]; then
        rm -rf /usr/share/wordpress/wp-content/themes/rabbitmq
        cp -r wordpress-theme /usr/share/wordpress/wp-content/themes/rabbitmq
    fi
fi

cp conf/robots.txt-${mode} ${build_dir}/robots.txt

if [ -d ${site_dir}/site/${version} ] ; then
    mv ${site_dir}/site/${version} ${old_dir}
fi

if [ ${mode} = previous ] ; then
    mkdir -p ${site_dir}/site
    mv ${build_dir} ${site_dir}/site/${version}
else
    mv ${build_dir} ${site_dir}/site
fi

if [ -d /etc/apache2/sites-available/ ]; then
    cp conf/${site}* /etc/apache2/sites-available/
    a2ensite ${site}
    /etc/init.d/apache2 reload
fi

rm -rf ${old_dir}

if [ $mode = www ] ; then
    if [ ! -e /etc/apache2/sites-enabled/www.rabbitmq.com-ssl.conf ]; then
        echo "*** Note site www.rabbitmq.com-ssl is not enabled. Please enable manually if necessary. ***"
    fi

    sed "s|@USER@|$mirror_user|" <conf/refresh-site.cron >/etc/cron.d/refresh-site
fi
