#!/bin/sh

SRV_DIR=/srv/www.rabbitmq.com

# Mirror the external feeds that appear on the rabbit web site

feeds_dir="$1"
[ -z "$feeds_dir" ] && feeds_dir=$SRV_DIR/feeds

mirror_feed () {
    url="$1"
    file="$2"

    tmpfile="/tmp/feed.$$"
    
    # Twitter seems to be sometimes returning a short HTML document
    # rather than the expected feed.  Discard it.
    wget -q -O "$tmpfile" "$url" \
        && ! head -1 "$tmpfile" | grep -i '^<!DOCTYPE html ' >/dev/null 2>&1 \
        && mv "$tmpfile" "$file"
    rm -f "$tmpfile"
}

mirror_feed 'http://search.twitter.com/search.atom?q=rabbitmq' $feeds_dir/twitter.atom
$SRV_DIR/code/compile $SRV_DIR/site-src $SRV_DIR/site index.xml