<?xml version="1.0"?>
    <table class="styled-table" xmlns="http://www.w3.org/1999/xhtml">
      <tr>
        <th>Protocol Version</th>
        <th>Documentation (PDF)</th>
        <th>Machine-Readable Spec (XML)</th>
      </tr>
      <tr>
        <td>AMQP 0-9-1 (incl. extensions)</td>
        <td></td>
        <td>
          <a href="resources/specs/amqp0-9-1.extended.xml">Full</a> |
          <a href="resources/specs/amqp0-9-1.stripped.extended.xml">BSD-licensed</a>
        </td>
      </tr>
      <tr>
        <td>AMQP 0-9-1</td>
        <td>
          <a href="resources/specs/amqp0-9-1.pdf">Specification</a> |
          <a href="resources/specs/amqp-xml-doc0-9-1.pdf">Generated Doc</a>
        </td>
        <td>
          <a href="resources/specs/amqp0-9-1.xml">Full</a> |
          <a href="resources/specs/amqp0-9-1.stripped.xml">BSD-licensed</a>
        </td>
      </tr>
      <tr>
        <td>AMQP 0-9</td>
        <td>
          <a href="resources/specs/amqp0-9.pdf">Specification</a> |
          <a href="resources/specs/amqp-xml-doc0-9.pdf">Generated Doc</a>
        </td>
        <td>
          <a href="resources/specs/amqp0-9.xml">Full</a> |
          <a href="resources/specs/amqp0-9.stripped.xml">BSD-licensed</a>
        </td>
      </tr>
      <tr>
        <td>AMQP 0-8</td>
        <td>
          <a href="resources/specs/amqp0-8.pdf">Specification</a> |
          <a href="resources/specs/amqp-xml-doc0-8.pdf">Generated Doc</a>
        </td>
        <td>
          <a href="resources/specs/amqp0-8.xml">Full</a> |
          <a href="resources/specs/amqp0-8.stripped.xml">BSD-licensed</a>
        </td>
      </tr>
    </table>
