<?xml version="1.0"?>
<!--
Copyright (c) 2005-2024 Broadcom. All Rights Reserved. The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.

All rights reserved. This program and the accompanying materials
are made available under the terms of the under the Apache License,
Version 2.0 (the "License”); you may not use this file except in compliance
with the License. You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
    <table class="styled-table" xmlns="http://www.w3.org/1999/xhtml">
      <tr>
        <th>Protocol Version</th>
        <th>Documentation (PDF)</th>
        <th>Machine-Readable Spec (XML)</th>
      </tr>
      <tr>
        <td>AMQP 0-9-1 (incl. extensions)</td>
        <td></td>
        <td>
          <a href="resources/specs/amqp0-9-1.extended.xml">Full</a> |
          <a href="resources/specs/amqp0-9-1.stripped.extended.xml">BSD-licensed</a>
        </td>
      </tr>
      <tr>
        <td>AMQP 0-9-1</td>
        <td>
          <a href="resources/specs/amqp0-9-1.pdf">Specification</a> |
          <a href="resources/specs/amqp-xml-doc0-9-1.pdf">Generated Doc</a>
        </td>
        <td>
          <a href="resources/specs/amqp0-9-1.xml">Full</a> |
          <a href="resources/specs/amqp0-9-1.stripped.xml">BSD-licensed</a>
        </td>
      </tr>
      <tr>
        <td>AMQP 0-9</td>
        <td>
          <a href="resources/specs/amqp0-9.pdf">Specification</a> |
          <a href="resources/specs/amqp-xml-doc0-9.pdf">Generated Doc</a>
        </td>
        <td>
          <a href="resources/specs/amqp0-9.xml">Full</a> |
          <a href="resources/specs/amqp0-9.stripped.xml">BSD-licensed</a>
        </td>
      </tr>
      <tr>
        <td>AMQP 0-8</td>
        <td>
          <a href="resources/specs/amqp0-8.pdf">Specification</a> |
          <a href="resources/specs/amqp-xml-doc0-8.pdf">Generated Doc</a>
        </td>
        <td>
          <a href="resources/specs/amqp0-8.xml">Full</a> |
          <a href="resources/specs/amqp0-8.stripped.xml">BSD-licensed</a>
        </td>
      </tr>
    </table>
