<?xml version="1.0"?>
    <table class="styled-table" xmlns="http://www.w3.org/1999/xhtml">
      <tr>
        <th>Protocol Version</th>
        <th colspan="3">Downloads</th>
      </tr>
      <tr>
        <td>AMQP 0-9-1 (incl. extensions)</td>
        <td></td>
        <td></td>
        <td><a href="resources/specs/amqp0-9-1.extended.xml">Definitions (xml)</a></td>
      </tr>
      <tr>
        <td>AMQP 0-9-1</td>
        <td><a href="resources/specs/amqp0-9-1.pdf">Specification (pdf)</a></td>
        <td><a href="resources/specs/amqp-xml-doc0-9-1.pdf">Documentation (pdf)</a></td>
        <td><a href="resources/specs/amqp0-9-1.xml">Definitions (xml)</a></td>
      </tr>
      <tr>
        <td>AMQP 0-9</td>
        <td><a href="resources/specs/amqp0-9.pdf">Specification (pdf)</a></td>
        <td><a href="resources/specs/amqp-xml-doc0-9.pdf">Documentation (pdf)</a></td>
        <td><a href="resources/specs/amqp0-9.xml">Definitions (xml)</a></td>
      </tr>
      <tr>
        <td>AMQP 0-8</td>
        <td><a href="resources/specs/amqp0-8.pdf">Specification (pdf)</a></td>
        <td><a href="resources/specs/amqp-xml-doc0-8.pdf">Documentation (pdf)</a></td>
        <td><a href="resources/specs/amqp0-8.xml">Definitions (xml)</a></td>
      </tr>
    </table>
