<?xml version="1.0"?>
<!DOCTYPE p [
<!ENTITY % entities SYSTEM "rabbit.ent" >
%entities;
]>
        <p>
          Contained in the tarball is a directory named
          <code>rabbitmq_server-&version-server;</code>. You should
          extract this into somewhere appropriate for application
          binaries on your system.  The <code>sbin</code> directory
          will be found in this directory.
        </p>