<?xml version="1.0"?>
<!DOCTYPE p [
<!ENTITY % entities SYSTEM "rabbit.ent" >
%entities;
]>
<!--
Copyright (c) 2007-2018 Pivotal Software, Inc.

All rights reserved. This program and the accompanying materials
are made available under the terms of the under the Apache License,
Version 2.0 (the "License”); you may not use this file except in compliance
with the License. You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

        <p>
          Contained in the tarball is a directory named
          <code>rabbitmq_server-&version-server;</code>. This directory is the node base directory. It should be
          moved to a suitable application directory on the system, such as <code>/usr/local</code>.
          The <code>sbin</code> directory in that directory contains server and <a href="/cli.html">CLI tool</a> scripts.
          It is a good candidate for including into <code>PATH</code>.
        </p>
