<?xml version="1.0"?>
<doc:section xmlns:doc="http://www.rabbitmq.com/namespaces/ad-hoc/doc"
             xmlns:xi="http://www.w3.org/2003/XInclude"
             name="windows-quirks">
  <doc:heading>Windows-specific Issues</doc:heading>
  <p>
    We aim to make RabbitMQ a first-class citizen on
    Windows. However, sometimes there are circumstances beyond our
    control. Please consult the <a href="windows-quirks.html">Windows-specific Issues</a> page.
  </p>
</doc:section>
