<?xml version="1.0"?>
<!--
Copyright (C) 2007-2015 Pivotal Software, Inc. 

All rights reserved. This program and the accompanying materials
are made available under the terms of the under the Apache License, 
Version 2.0 (the "License”); you may not use this file except in compliance 
with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<doc:subsection xmlns:doc="http://www.rabbitmq.com/namespaces/ad-hoc/doc" name="chef-puppet-bosh">
  <doc:heading>Configuration Management Tools</doc:heading>
  <p>
    Configuration management tools (e.g. Chef, Puppet, BOSH) provide assistance
    with system limit tuning. Our <a href="devtools.html#devops-tools">developer tools</a> guide
    lists relevant modules and projects.
  </p>
</doc:subsection>
