<?xml version="1.0"?>
<doc:subsection xmlns:doc="http://www.rabbitmq.com/namespaces/ad-hoc/doc" name="chef-puppet-bosh">
  <doc:heading>Configuration Management Tools</doc:heading>
  <p>
    Configuration management tools (e.g. Chef, Puppet, BOSH) provide assistance
    with system limit tuning. Our <a href="devtools.html#devops-tools">developer tools</a> guide
    lists relevant modules and projects.
  </p>
</doc:subsection>
