<?xml version="1.0"?>
      <ul id="tutorials">
        <li id="tutorial-one">
          <h2><span class="tute-num">1</span> <a href="tutorial-one-python.html">"Hello World!"</a></h2>
          <p>
            The simplest thing that does <em>something</em>
          </p>
          <p><img src="img/tutorials/python-one.png" width="180"  /></p>
          <ul>
            <li>
              <a href="tutorial-one-python.html">In Python</a>
            </li>
            <li>
              <a href="tutorial-one-java.html">In Java</a>
            </li>
          </ul>
        </li>
        <li id="tutorial-two">
          <h2><span class="tute-num">2</span> <a href="tutorial-two-python.html">Work queues</a></h2>
          <p>
            Distributing tasks among workers
          </p>
          <p><img src="img/tutorials/python-two.png" height="50" width="180" /></p>
          <ul>
            <li>
              <a href="tutorial-two-python.html">In Python</a>
            </li>
            <li>
              <a href="tutorial-two-java.html">In Java</a>
             </li> 
          </ul>
        </li>
        <li id="tutorial-three">
          <h2><span class="tute-num">3</span> <a href="tutorial-three-python.html">Publish/Subscribe</a></h2>
          <p>
            Sending messages to many consumers at once
          </p>
          <p><img src="img/tutorials/python-three.png" height="40" width="180" /></p>
          <ul>
            <li>
              <a href="tutorial-three-python.html">In Python</a>
            </li>
            <li>
                 <a href="tutorial-three-java.html">In Java</a>
                 </li>
          </ul>
        </li>

        <li id="tutorial-four">
          <h2><span class="tute-num">4</span> <a href="tutorial-four-python.html">Routing</a></h2>
          <p>
	    Receiving messages selectively
          </p>
          <p><img src="img/tutorials/python-four.png" height="60" width="180" /></p>
          <ul>
            <li>
              <a href="tutorial-four-python.html">In Python</a>
            </li>
            <li>
                 <a href="tutorial-four-java.html">In Java</a>
                 </li>
          </ul>
        </li>

        <li id="tutorial-five">
          <h2><span class="tute-num">5</span> <a href="tutorial-five-python.html">Topics</a></h2>
          <p>
	    Receiving messages based on a pattern
          </p>
          <p><img src="img/tutorials/python-five.png" height="40" width="180" /></p>
          <ul>
            <li>
              <a href="tutorial-five-python.html">In Python</a>
            </li>
            <li>
                 <a href="tutorial-five-java.html">In Java</a>
                 </li>
          </ul>
        </li>
      </ul>
