<?xml version="1.0"?>
      <ul id="tutorials">
        <li class="tutorial-one">
          <h2><span class="tute-num">1</span> <a href="tutorial-one-python.html">"Hello World!"</a></h2>
          <p>
            The simplest thing that does <em>something</em>
          </p>
          <p><img src="img/tutorials/python-one.png" width="180"/></p>
          <ul>
            <li>
              <a href="tutorial-one-python.html">In Python</a>
            </li>
            <li>
              <a href="tutorial-one-java.html">In Java</a>
            </li>
          </ul>
        </li>
        <li class="tutorial-two">
          <h2><span class="tute-num">2</span> <a href="tutorial-two-python.html">Work queues</a></h2>
          <p>
            Distributing tasks among workers
          </p>
          <p><img src="img/tutorials/python-two.png" width="180"/></p>
          <ul>
            <li>
              <a href="tutorial-two-python.html">In Python</a>
            </li>
            <!-- <li>
                 <a href="tutorial-two-java.html">In Java</a>
                 </li> -->
          </ul>
        </li>
        <li class="tutorial-three">
          <h2><span class="tute-num">3</span> <a href="tutorial-three-python.html">Broadcast</a></h2>
          <p>
            Sending messages to many consumers at once
          </p>
          <p><img src="img/tutorials/python-three.png" width="180"/></p>
          <ul>
            <li>
              <a href="tutorial-three-python.html">In Python</a>
            </li>
            <!-- <li>
                 <a href="tutorial-three-java.html">In Java</a>
                 </li> -->
          </ul>
        </li>
      </ul>
