<?xml version="1.0" ?>
  <div class="aside">
    <h3>Where to get help</h3>
    <p>
        If you're having trouble going through this tutorial you can post
        a message to the <a
        href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbitmq-discuss
        mailing list</a> or join the <a
        href="irc://irc.freenode.net/rabbitmq">#rabbitmq irc channel</a>.
    </p>
  </div>
