## The contents of this file are subject to the Mozilla Public License
## Version 1.1 (the "License"); you may not use this file except in
## compliance with the License. You may obtain a copy of the License
## at http://www.mozilla.org/MPL/
#
## Software distributed under the License is distributed on an "AS IS"
## basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
## the License for the specific language governing rights and
## limitations under the License.
#
# Copyright (c) 2023 VMware, Inc. or its affiliates.  All rights reserved.

ARG ubuntu_version="22.04"

FROM ubuntu:$ubuntu_version as builder

ARG hugo_version="0.119.0"

ENV LANG='C.UTF-8'

RUN  apt-get clean && \
       apt-get update && \
       apt-get install -y --fix-missing --no-install-recommends \
       apt-transport-https \
       wget \
       build-essential \
       zlib1g-dev \
       libssl-dev \
       ca-certificates \
       jq

RUN wget -O hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v$hugo_version/hugo_${hugo_version}_Linux-64bit.tar.gz && \
    tar xf hugo.tar.gz

FROM ubuntu:$ubuntu_version

ENV LANG='C.UTF-8'

COPY --from=builder /hugo /usr/bin/hugo

ENV TZ=Etc/UTC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get clean && \
       apt-get update && \
       apt-get install -y --fix-missing --no-install-recommends \
       apt-transport-https \
       wget \
       build-essential \
       ca-certificates \
       curl \
       debhelper \
       elinks \
       fakeroot \
       git \
       gnupg \
       libfile-fcntllock-perl \
       mandoc \
       nsis \
       openssh-client \
       python3 \
       python3-lxml \
       python3-markdown \
       python3-pygments \
       python3-simplejson \
       rpm \
       rsync \
       tofrodos \
       unzip \
       xmlto \
       xsltproc \
       zip \
       curl \
       procps

RUN mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    NODE_MAJOR=18 && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && \
    apt-get install nodejs -y && \
    mkdir -p /root/.wrangler/config/ && \
    npm install -g wrangler

RUN node --version && wrangler version
