<div>
  <h2>Production [Non-]Suitability Disclaimer</h2>
  <p>
    Please keep in mind that this and other tutorials are, well, tutorials.
    They demonstrate one new concept at a time and may intentionally oversimplify some things and leave out others. For example topics such as
    connection management, error handling, connection recovery, concurrency and metric collection are largely omitted
    for the sake of brevity. Such simplified code should not be considered production ready.
  </p>
  <p>
    Please take a look at the rest of the <a href="/documentation.html">documentation</a> before going live with your app.
    We particularly recommend the following guides: <a href="../confirms.html">Publisher Confirms and Consumer Acknowledgements</a>,
    <a href="/production-checklist.html">Production Checklist</a> and <a href="/monitoring.html">Monitoring</a>.
  </p>
</div>
