<?xml version="1.0" encoding="utf-8" ?>
<!--
Copyright (c) 2005-2024 Broadcom. All Rights Reserved. The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.

All rights reserved. This program and the accompanying materials
are made available under the terms of the under the Apache License,
Version 2.0 (the "License”); you may not use this file except in compliance
with the License. You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<table id="tutorials" xmlns="http://www.w3.org/1999/xhtml">
  <tr>
  <td id="tutorial-one">
    <h2><span class="tute-num">1</span> <a href="./tutorial-one-python.html">"Hello World!"</a></h2>
    <p>
      The simplest thing that does <em>something</em>
    </p>
    <p><img src="../img/tutorials/python-one.png" width="180" alt="(P) -> [|||] -> (C)" /></p>
    <ul>
      <li><a href="./tutorial-one-python.html">Python</a></li>
      <li><a href="./tutorial-one-java.html">Java</a></li>
      <li><a href="./tutorial-one-spring-amqp.html">Spring AMQP</a></li>
      <li><a href="./tutorial-one-ruby.html">Ruby</a></li>
      <li><a href="./tutorial-one-php.html">PHP</a></li>
      <li><a href="./tutorial-one-dotnet.html">C#</a></li>
      <li><a href="./tutorial-one-javascript.html">JavaScript</a></li>
      <li><a href="./tutorial-one-go.html">Go</a></li>
      <li><a href="./tutorial-one-elixir.html">Elixir</a></li>
      <li><a href="./tutorial-one-objectivec.html">Objective-C</a></li>
      <li><a href="./tutorial-one-swift.html">Swift</a></li>
    </ul>
  </td>

  <td id="tutorial-two">
    <h2><span class="tute-num">2</span> <a href="./tutorial-two-python.html">Work queues</a></h2>
    <p>
      Distributing tasks among workers (the <a href="http://www.enterpriseintegrationpatterns.com/patterns/messaging/CompetingConsumers.html">competing consumers pattern</a>)
    </p>
    <p><img src="../img/tutorials/python-two.png" width="180" alt="Producer -> Queue -> Consuming: Work Queue used to distribute time-consuming tasks among multiple workers." /></p>
    <ul>
        <li><a href="./tutorial-two-python.html">Python</a></li>
        <li><a href="./tutorial-two-java.html">Java</a></li>
        <li><a href="./tutorial-two-spring-amqp.html">Spring AMQP</a></li>
        <li><a href="./tutorial-two-ruby.html">Ruby</a></li>
        <li><a href="./tutorial-two-php.html">PHP</a></li>
        <li><a href="./tutorial-two-dotnet.html">C#</a></li>
        <li><a href="./tutorial-two-javascript.html">JavaScript</a></li>
        <li><a href="./tutorial-two-go.html">Go</a></li>
        <li><a href="./tutorial-two-elixir.html">Elixir</a></li>
        <li><a href="./tutorial-two-objectivec.html">Objective-C</a></li>
        <li><a href="./tutorial-two-swift.html">Swift</a></li>
    </ul>
  </td>

  <td id="tutorial-three">
    <h2><span class="tute-num">3</span> <a href="./tutorial-three-python.html">Publish/Subscribe</a></h2>
    <p>
      Sending messages to many consumers at once
    </p>
    <p><img src="../img/tutorials/python-three.png" height="50" width="180" alt="Producer -> Queue -> Consuming: deliver a message to multiple consumers." /></p>
    <ul>
      <li><a href="./tutorial-three-python.html">Python</a></li>
      <li><a href="./tutorial-three-java.html">Java</a></li>
      <li><a href="./tutorial-three-spring-amqp.html">Spring AMQP</a></li>
      <li><a href="./tutorial-three-ruby.html">Ruby</a></li>
      <li><a href="./tutorial-three-php.html">PHP</a></li>
      <li><a href="./tutorial-three-dotnet.html">C#</a></li>
      <li><a href="./tutorial-three-javascript.html">JavaScript</a></li>
      <li><a href="./tutorial-three-go.html">Go</a></li>
      <li><a href="./tutorial-three-elixir.html">Elixir</a></li>
      <li><a href="./tutorial-three-objectivec.html">Objective-C</a></li>
      <li><a href="./tutorial-three-swift.html">Swift</a></li>
    </ul>
  </td>
  </tr>

  <tr>
  <td id="tutorial-four">
    <h2><span class="tute-num">4</span> <a href="./tutorial-four-python.html">Routing</a></h2>
    <p>
      Receiving messages selectively
    </p>
    <p><img src="../img/tutorials/python-four.png" height="50" width="180" alt="Producer -> Queue -> Consuming: subscribe to a subset of the messages only." /></p>
    <ul>
      <li><a href="./tutorial-four-python.html">Python</a></li>
      <li><a href="./tutorial-four-java.html">Java</a></li>
      <li><a href="./tutorial-four-spring-amqp.html">Spring AMQP</a></li>
      <li><a href="./tutorial-four-ruby.html">Ruby</a></li>
      <li><a href="./tutorial-four-php.html">PHP</a></li>
      <li><a href="./tutorial-four-dotnet.html">C#</a></li>
      <li><a href="./tutorial-four-javascript.html">JavaScript</a></li>
      <li><a href="./tutorial-four-go.html">Go</a></li>
      <li><a href="./tutorial-four-elixir.html">Elixir</a></li>
      <li><a href="./tutorial-four-objectivec.html">Objective-C</a></li>
      <li><a href="./tutorial-four-swift.html">Swift</a></li>
    </ul>
  </td>

  <td id="tutorial-five">
    <h2><span class="tute-num">5</span> <a href="./tutorial-five-python.html">Topics</a></h2>
    <p>
      Receiving messages based on a pattern (topics)
    </p>
    <p><img src="../img/tutorials/python-five.png" height="50" width="180" alt="Producer -> Queue -> Consuming: receiving messages based on a pattern (topics)." /></p>
    <ul>
      <li><a href="./tutorial-five-python.html">Python</a></li>
      <li><a href="./tutorial-five-java.html">Java</a></li>
      <li><a href="./tutorial-five-spring-amqp.html">Spring AMQP</a></li>
      <li><a href="./tutorial-five-ruby.html">Ruby</a></li>
      <li><a href="./tutorial-five-php.html">PHP</a></li>
      <li><a href="./tutorial-five-dotnet.html">C#</a></li>
      <li><a href="./tutorial-five-javascript.html">JavaScript</a></li>
      <li><a href="./tutorial-five-go.html">Go</a></li>
      <li><a href="./tutorial-five-elixir.html">Elixir</a></li>
      <li><a href="./tutorial-five-objectivec.html">Objective-C</a></li>
      <li><a href="./tutorial-five-swift.html">Swift</a></li>
    </ul>
  </td>

  <td id="tutorial-six">
    <h2><span class="tute-num">6</span> <a href="./tutorial-six-python.html">RPC</a></h2>
    <p>
      <a href="http://www.enterpriseintegrationpatterns.com/patterns/messaging/RequestReply.html">Request/reply pattern</a> example
    </p>
    <p><img src="../img/tutorials/python-six.png" height="50" width="180" alt="Producer -> Queue -> Consuming: RPC (Remote Procedure Call), the request/reply pattern." /></p>
    <ul>
      <li><a href="./tutorial-six-python.html">Python</a></li>
      <li><a href="./tutorial-six-java.html">Java</a></li>
      <li><a href="./tutorial-six-spring-amqp.html">Spring AMQP</a></li>
      <li><a href="./tutorial-six-ruby.html">Ruby</a></li>
      <li><a href="./tutorial-six-php.html">PHP</a></li>
      <li><a href="./tutorial-six-dotnet.html">C#</a></li>
      <li><a href="./tutorial-six-javascript.html">JavaScript</a></li>
      <li><a href="./tutorial-six-go.html">Go</a></li>
      <li><a href="./tutorial-six-elixir.html">Elixir</a></li>
    </ul>
  </td>
  </tr>
  <tr>
  <td id="tutorial-seven">
    <h2><span class="tute-num">7</span> <a href="./tutorial-seven-java.html">Publisher Confirms</a></h2>
    <p>
      Reliable publishing with publisher confirms
    </p>
    <ul>
      <li><a href="./tutorial-seven-java.html">Java</a></li>
      <li><a href="./tutorial-seven-dotnet.html">C#</a></li>
      <li><a href="./tutorial-seven-php.html">PHP</a></li>
    </ul>
  </td>
  <td class="tutorial-empty"></td>
  <td class="tutorial-empty"></td>
  </tr>
</table>
