<?xml version="1.0" encoding="utf-8" ?>
<!--
Copyright (c) 2005-2024 Broadcom. All Rights Reserved. The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.

All rights reserved. This program and the accompanying materials
are made available under the terms of the under the Apache License,
Version 2.0 (the "License”); you may not use this file except in compliance
with the License. You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
  <div class="aside" style="margin-top: -10px;" xmlns="http://www.w3.org/1999/xhtml">
    <h3>Prerequisites</h3>
    <p>
      This tutorial assumes RabbitMQ is <a href="../download.html">installed</a> and running
      on <code>localhost</code> on the <a href="../networking.html#ports">standard port</a> (<code>5672</code>). In case you use
      a different host, port or credentials, connections settings would require adjusting.
    </p>

    <h3>Where to get help</h3>
    <p>
        If you're having trouble going through this tutorial you can contact us through the
        <a href="https://groups.google.com/forum/#!forum/rabbitmq-users">mailing list</a>
        or <a href="https://rabbitmq.com/slack/">RabbitMQ community Slack</a>.
    </p>
  </div>
