<?xml version="1.0" ?>
  <div class="aside" xmlns="http://www.w3.org/1999/xhtml">
    <h3>Prerequisites</h3>
    <p>
      This tutorial assumes RabbitMQ is <a href="/download.html">installed</a> and running
      on <code>localhost</code> on standard port (<code>5672</code>). In case you use
      a different host, port or credentials, connections settings would require adjusting.
    </p>

    <h3>Where to get help</h3>
    <p>
        If you're having trouble going through this tutorial you can
        <a href="https://groups.google.com/forum/#!forum/rabbitmq-users">contact us</a> through the mailing list.
    </p>
  </div>
