<?xml version="1.0" encoding="utf-8" ?>
<!--
Copyright (C) 2007-2015 Pivotal Software, Inc. 

All rights reserved. This program and the accompanying materials
are made available under the terms of the under the Apache License, 
Version 2.0 (the "License”); you may not use this file except in compliance 
with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
      <ul id="tutorials" xmlns="http://www.w3.org/1999/xhtml">

        <li id="tutorial-one">
          <h2><span class="tute-num">1</span> <a href="/tutorials/tutorial-one-python.html">"Hello World!"</a></h2>
          <p>
            The simplest thing that does <em>something</em>
          </p>
          <p><img src="/img/tutorials/python-one.png" width="180"  /></p>
          <p>
          <a href="/tutorials/tutorial-one-python.html">Python</a>
          |
          <a href="/tutorials/tutorial-one-java.html">Java</a>
          |
          <a href="/tutorials/tutorial-one-ruby.html">Ruby</a>
          |
          <a href="/tutorials/tutorial-one-php.html">PHP</a>
          |
          <a href="/tutorials/tutorial-one-dotnet.html">C#</a>
          </p>
        </li>

        <li id="tutorial-two">
          <h2><span class="tute-num">2</span> <a href="/tutorials/tutorial-two-python.html">Work queues</a></h2>
          <p>
            Distributing tasks among workers
          </p>
          <p><img src="/img/tutorials/python-two.png" height="50" width="180" /></p>
          <p>
          <a href="/tutorials/tutorial-two-python.html">Python</a>
          |
          <a href="/tutorials/tutorial-two-java.html">Java</a>
          |
          <a href="/tutorials/tutorial-two-ruby.html">Ruby</a>
          |
          <a href="/tutorials/tutorial-two-php.html">PHP</a>
          |
          <a href="/tutorials/tutorial-two-dotnet.html">C#</a>
          </p>
        </li>

        <li id="tutorial-three">
          <h2><span class="tute-num">3</span> <a href="/tutorials/tutorial-three-python.html">Publish/Subscribe</a></h2>
          <p>
            Sending messages to many consumers at once
          </p>
          <p><img src="/img/tutorials/python-three.png" height="50" width="180" /></p>
          <p>
          <a href="/tutorials/tutorial-three-python.html">Python</a>
          |
          <a href="/tutorials/tutorial-three-java.html">Java</a>
          |
          <a href="/tutorials/tutorial-three-ruby.html">Ruby</a>
          |
          <a href="/tutorials/tutorial-three-php.html">PHP</a>
          |
          <a href="/tutorials/tutorial-three-dotnet.html">C#</a>
          </p>
        </li>

        <li id="tutorial-four">
          <h2><span class="tute-num">4</span> <a href="/tutorials/tutorial-four-python.html">Routing</a></h2>
          <p>
            Receiving messages selectively
          </p>
          <p><img src="/img/tutorials/python-four.png" height="50" width="180" /></p>
          <p>
          <a href="/tutorials/tutorial-four-python.html">Python</a>
          |
          <a href="/tutorials/tutorial-four-java.html">Java</a>
          |
          <a href="/tutorials/tutorial-four-ruby.html">Ruby</a>
          |
          <a href="/tutorials/tutorial-four-php.html">PHP</a>
          |
          <a href="/tutorials/tutorial-four-dotnet.html">C#</a>
          </p>
        </li>

        <li id="tutorial-five">
          <h2><span class="tute-num">5</span> <a href="/tutorials/tutorial-five-python.html">Topics</a></h2>
          <p>
            Receiving messages based on a pattern
          </p>
          <p><img src="/img/tutorials/python-five.png" height="50" width="180" /></p>
          <p>
          <a href="/tutorials/tutorial-five-python.html">Python</a>
          |
          <a href="/tutorials/tutorial-five-java.html">Java</a>
          |
          <a href="/tutorials/tutorial-five-ruby.html">Ruby</a>
          |
          <a href="/tutorials/tutorial-five-php.html">PHP</a>
          |
          <a href="/tutorials/tutorial-five-dotnet.html">C#</a>
          </p>
        </li>

        <li id="tutorial-six">
          <h2><span class="tute-num">6</span> <a href="/tutorials/tutorial-six-python.html">RPC</a></h2>
          <p>
            Remote procedure call implementation
          </p>
          <p><img src="/img/tutorials/python-six.png" height="50" width="180" /></p>
          <p>
          <a href="/tutorials/tutorial-six-python.html">Python</a>
          |
          <a href="/tutorials/tutorial-six-java.html">Java</a>
          |
          <a href="/tutorials/tutorial-six-ruby.html">Ruby</a>
          |
          <a href="/tutorials/tutorial-six-php.html">PHP</a>
          |
          <a href="/tutorials/tutorial-six-dotnet.html">C#</a>
          </p>
        </li>
      </ul>
